frr version 10.2
frr defaults traditional
hostname pe2
service integrated-vtysh-config
!
interface lo
 ip address 10.255.0.2/32
 ip router isis CORE
!
interface eth1
 ip address 10.0.21.1/31
 ip router isis CORE
 isis network point-to-point
!
interface eth2
 ip address 10.0.22.1/31
 ip router isis CORE
 isis network point-to-point
!
router isis CORE
 net 49.0001.0000.0000.0002.00
 is-type level-2-only
 metric-style wide
 segment-routing on
 segment-routing global-block 16000 23999
 segment-routing node-msd 8
!
router bgp 65000
 bgp router-id 10.255.0.2
 no bgp default ipv4-unicast
 neighbor 10.255.0.1 remote-as 65000
 neighbor 10.255.0.1 update-source lo
 address-family ipv4 vpn
  neighbor 10.255.0.1 activate
 exit-address-family
!
ip vrf CUSTOMER_A
 rd 65000:100
 route-target import 65000:100
 route-target export 65000:100
exit-vrf
!
ip vrf CUSTOMER_B
 rd 65000:200
 route-target import 65000:200
 route-target export 65000:200
exit-vrf
