frr version 10.2
frr defaults traditional
hostname ce-b
service integrated-vtysh-config
!
interface lo
 ip address 172.20.20.1/32
!
router bgp 65200
 bgp router-id 172.20.20.1
 neighbor 198.51.100.1 remote-as 65000
 neighbor 198.51.100.3 remote-as 65000
 network 172.20.20.1/32
