frr version 10.2
frr defaults traditional
hostname ce-a
service integrated-vtysh-config
!
interface lo
 ip address 172.20.10.1/32
!
router bgp 65100
 bgp router-id 172.20.10.1
 neighbor 192.0.2.1 remote-as 65000
 neighbor 192.0.2.3 remote-as 65000
 network 172.20.10.1/32
